name: Auto Deploy to Render

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ https://api.render.com/deploy/srv-d6jo6k75r7bs739jadf0?key=KBJ5-bLDboQ }}
